### PR TITLE
Feat : Added avatar

### PR DESCRIPTION
**Pull request by devananth**
Added Avatar component
         => It has 4 different sizes and 3 variations of avatars

Variations : 
         => Image Avatar
                    - Round Image Avatar
                    - Square Image Avatar
Avatars

          => Text Avatar 

Fixed some minor changes related previous PR

**Live URL** :  https://deploy-preview-2--wonderful-wescoff-6f3f26.netlify.app/component/avatar/avatar

### CODE REVIEW

**Review by shivanigangadharan — APPROVED** [review]
Unable to see anything in the deploy preview link but from the video, the avatars with different variations look great. Code also looks good to me. 👍

**Review by ashishnnnnn — APPROVED** [review]
Code seems structured :+1:

**Comment by devananth** [comment]
> Unable to see anything in the deploy preview link but from the video, the avatars with different variations look great. Code also looks good to me. 👍

**Comment by devananth** [comment]
**Merging PR**

**Pull request merged**
