### PR TITLE
WD : Feat-Buttons : Add : Added new component button

### PR DESCRIPTION
**Pull request by devananth**
# Added Button 
           It has 5 variations.
                     - Primary Buttons
                     - Secondary Buttons
                     - Disabled Buttons
                     - Different Size of Buttons
                     - Floating Action Buttons

 **Live URL** : https://deploy-preview-4--wonderful-wescoff-6f3f26.netlify.app/components/button/button

### CODE REVIEW

**Review by ivinayakg — APPROVED** [review]
looks good go ahead and merge it

**Review by amarphule — COMMENTED** [review]
Code structure looks good. You followed all the rules. 
Just one suggestion, In some cases you used color names instead of variable names. Do update that to keep code consistent.

**Review by tanishk15sharma — APPROVED** [review]
good to merge

**Comment by devananth** [comment]
> looks good go ahead and merge it

Thanks for the review.

**Comment by devananth** [comment]
> Code structure looks good. You followed all the rules. Just one suggestion, In some cases you used color names instead of variable names. Do update that to keep code consistent.

Thanks for the review , will fix it

**Comment by devananth** [comment]
> good to merge

Thanks for the review

**Pull request merged**
